// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-7cQ-xiq6Pukq1pi06RqDHMAj15wiiU4',
    appId: '1:1064497156958:web:77b2b66173596da96035cf',
    messagingSenderId: '1064497156958',
    projectId: 'studyconnect-ea76d',
    authDomain: 'studyconnect-ea76d.firebaseapp.com',
    storageBucket: 'studyconnect-ea76d.firebasestorage.app',
    measurementId: 'G-X7TXQLYHE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPynwS1dOXdm7Uh69hKT971auW9GjT2TQ',
    appId: '1:1064497156958:android:5bdc77aa17e300b56035cf',
    messagingSenderId: '1064497156958',
    projectId: 'studyconnect-ea76d',
    storageBucket: 'studyconnect-ea76d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdmIXoPsJtZg0UKCm9FY1IqY6WsKvvFU',
    appId: '1:1064497156958:ios:a52a3b022248740d6035cf',
    messagingSenderId: '1064497156958',
    projectId: 'studyconnect-ea76d',
    storageBucket: 'studyconnect-ea76d.firebasestorage.app',
    iosBundleId: 'com.example.studyConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdmIXoPsJtZg0UKCm9FY1IqY6WsKvvFU',
    appId: '1:1064497156958:ios:a52a3b022248740d6035cf',
    messagingSenderId: '1064497156958',
    projectId: 'studyconnect-ea76d',
    storageBucket: 'studyconnect-ea76d.firebasestorage.app',
    iosBundleId: 'com.example.studyConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-7cQ-xiq6Pukq1pi06RqDHMAj15wiiU4',
    appId: '1:1064497156958:web:0f7e8036249136276035cf',
    messagingSenderId: '1064497156958',
    projectId: 'studyconnect-ea76d',
    authDomain: 'studyconnect-ea76d.firebaseapp.com',
    storageBucket: 'studyconnect-ea76d.firebasestorage.app',
    measurementId: 'G-1V646V06T7',
  );
}
